//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Propietaria_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public string Cedula_usuario { get; set; }
        public string NombreCalle_direccion { get; set; }
        public string Numero_direccion { get; set; }
        public string Sector_direccion { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
