//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Propietaria_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES
    {
        public int ID_transacciones { get; set; }
        public string ID_tarjeta { get; set; }
        public string ID_concurrencia { get; set; }
        public string nombreComercio_transacciones { get; set; }
        public string tipoComercio_transacciones { get; set; }
        public System.DateTime fecha_transacciones { get; set; }
        public decimal monto_transacciones { get; set; }
    
        public virtual TARJETA_CREDITO TARJETA_CREDITO { get; set; }
        public virtual TARJETA_DEBITO TARJETA_DEBITO { get; set; }
    }
}
